using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace NotificationPOCSystem.DAL.Models
{
    public class Employee
    {
        [Key]
        public decimal EmployeeID { get; set; }
        public decimal DeptID { get; set; }
        public decimal? SecID { get; set; }
        public decimal? BrID { get; set; }
        public decimal EmployeeCode { get; set; }
        public string? ArTitle { get; set; }
        public string? QualifyDetails { get; set; }
        public DateTime? AppmntDate { get; set; }
        public DateTime? CardAppmntDate { get; set; }
        public DateTime? ReAppmntDate { get; set; }
        public int? PerTitleID { get; set; }
        public string? ArName { get; set; }
        public string? newArname { get; set; }
        public string? FArName { get; set; }
        public string? MArName { get; set; }
        public string? LArName { get; set; }
        public string? FamilyArName { get; set; }
        public string? EnName { get; set; }
        public string? FEnName { get; set; }
        public string? MENName { get; set; }
        public string? LEnName { get; set; }
        public string? FamilyEnName { get; set; }
        public DateTime? BirthDate { get; set; }
        public int? Nationality { get; set; }
        public int? Sex { get; set; }
        public int? MaritalStat { get; set; }
        public int? Religion { get; set; }
        public string? OfficeTel { get; set; }
        public string? HomeTel { get; set; }
        public string? MobileTel { get; set; }
        public int? Pager { get; set; }
        public string? familyno { get; set; }
        public string? PassportNo { get; set; }
        public DateTime? PassportExpDt { get; set; }
        public int? PlacePassPort { get; set; }
        public string? ResNo { get; set; }
        public DateTime? ResExpDt { get; set; }
        public int? ContractType { get; set; }
        public int? Grade { get; set; }
        public decimal? BasicSal { get; set; }
        public int? BasicRatio { get; set; }
        public decimal? Fixed { get; set; }
        public decimal? Daily { get; set; }
        public decimal? HomeValue { get; set; }
        public decimal? Home { get; set; }
        public int? Qualify { get; set; }
        public int? PayRoll { get; set; }
        public int? Vacation { get; set; }
        public int? ExperienceYears { get; set; }
        public string? ArRemarks { get; set; }
        public string? EnRemarks { get; set; }
        public int? Children { get; set; }
        public int? InVacation { get; set; }
        public decimal? VacID { get; set; }
        public int? BankID { get; set; }
        public int? BranchID { get; set; }
        public string? Account { get; set; }
        public DateTime? IncDate { get; set; }
        public int? Edit { get; set; }
        public int? Lend { get; set; }
        public string? txtLend { get; set; }
        public string? reportgrade { get; set; }
        public string? LocalPass { get; set; }
        public int? PlaceLocalPass { get; set; }
        public int? vactableid { get; set; }
        public string? InsuranceNo { get; set; }
        public DateTime? fromdate { get; set; }
        public DateTime? todate { get; set; }
        public int? EndService { get; set; }
        public DateTime? EndServiceDate { get; set; }
        public DateTime? CardEndServiceDate { get; set; }
        public string? Reason { get; set; }
        public decimal? Balance { get; set; }
        public int? Absent { get; set; }
        public decimal? BalanceCash { get; set; }
        public decimal? Deducts { get; set; }
        public decimal? Adds { get; set; }
        public decimal? Die { get; set; }
        public decimal? Net { get; set; }
        public int? homeratio { get; set; }
        public decimal? DeductCode { get; set; }
        public DateTime? fromdate1 { get; set; }
        public int? op { get; set; }
        public int? Grade1 { get; set; }
        public DateTime? fromdate2 { get; set; }
        public int? OutTransfer { get; set; }
        public DateTime? OutTransferDate { get; set; }
        public int? OutDept { get; set; }
        public int? InTransfer { get; set; }
        public DateTime? InTransferDate { get; set; }
        public int? InDept { get; set; }
        public string? InFilecode2 { get; set; }
        public int? InOrderSet { get; set; }
        public int? Grade2 { get; set; }
        public int? Qualify1 { get; set; }
        public int? QualifyU { get; set; }
        public int? qualifyf { get; set; }
        public int? QualifyS { get; set; }
        public string? QualifyY { get; set; }
        public string? DeptEmpCode { get; set; }
        public int? Study { get; set; }
        public int? QualifyPlace { get; set; }
        public int? MNationality { get; set; }
        public string? MName { get; set; }
        public string? FName { get; set; }
        public string? MNum1 { get; set; }
        public string? MNum2 { get; set; }
        public string? MNum3 { get; set; }
        public string? FileCode1 { get; set; }
        public decimal? FileCode { get; set; }
        public string? FileCode2 { get; set; }
        public string? IDNum1 { get; set; }
        public string? IDNum2 { get; set; }
        public string? IDNum3 { get; set; }
        public string? IDNum4 { get; set; }
        public string? IDNUM { get; set; }
        public DateTime? IDIDate { get; set; }
        public DateTime? IDEDate { get; set; }
        public decimal? Br_Place_id { get; set; }
        public int? OrderSet { get; set; }
        public int? NoAttends { get; set; }
        public int? Activity_id { get; set; }
        public string? ImagePath { get; set; }
        public string? ImageType { get; set; }
        public byte[]? ImageSource1 { get; set; }
        public byte[]? ImageSource { get; set; }
        public decimal? TEmployeeid { get; set; }
        public string? JobDescription { get; set; }
        public int? Block { get; set; }
        public DateTime? BlockDate { get; set; }
        public int? BlockUser { get; set; }
        public string? BlockRemarks { get; set; }
        public decimal? Dept_Structure_Id { get; set; }
        public decimal? Dept_Branch_Id { get; set; }
        public int? QualificationEquivalent { get; set; }
        public DateTime? QualificationEquivalent_Date { get; set; }
        public decimal? QualificationEquivalent_userid { get; set; }
        public string? Email { get; set; }
        public int? Pension_Delete { get; set; }
        public int? Pension_Block { get; set; }
        public int? employerid { get; set; }
        public int? TitleId { get; set; }
        public string? provideHouse { get; set; }
        public DateTime? ProvideHouseDate { get; set; }
        public int TestPeriod { get; set; }
        public bool IsSessionActive { get; set; }
        public bool? IsDeleted { get; set; }
        public long? DeleteLogId { get; set; }
        public int? IsToWhomConcern { get; set; }
        public string? GradeName { get; set; }
        public string? ContractTypeName { get; set; }
        public int? NationalityTypeId { get; set; }
        public int? EndServiceUser { get; set; }
        public int? CancellationReason_Id { get; set; }
        public int? ReturnReason_Id { get; set; }
        public int? EndServiceReturnUser { get; set; }
        public bool? FinishTranferOut { get; set; }
        public int? GradePeriority { get; set; }
        public decimal? APIJobId { get; set; }
        public DateTime? TrabsferDate { get; set; }
        public decimal? NC_TotalSalary { get; set; }
        public string? NC_WorkLocation { get; set; }
        public DateTime? TransferInsideCreatedDate { get; set; }
        public int? JobSeekerId { get; set; }
        public bool? istemp { get; set; }
    }

}
